OrdererOrgs:
  - Name: Orderer
    Domain: pcxchg.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Asus
    Domain: Asus.com
    Template:
      Count: 2
    Users:
      Count: 2
  - Name: Amazon
    Domain: Amazon.com
    Template:
      Count: 2
    Users:
      Count: 2
  - Name: Dell
    Domain: Dell.com
    Template:
      Count: 2
    Users:
      Count: 2
  - Name: HP
    Domain: HP.com
    Template:
      Count: 2
    Users:
      Count: 2
